---

- name: prepare container
  hosts: all
  gather_facts: true

  roles:
    - role: bodsch.database.postgresql

- name: converge
  hosts: database
  any_errors_fatal: false
  become: false

  roles:
    - role: bodsch.database.postgresql_databases
