---

mysqltuner_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/mysqltuner', true) }}/{{ mysqltuner_version }}"

mysqltuner_remote_tmp_directory: /root/.ansible/mysqltuner

mysqltuner_download: false
mysqltuner_download_directory: "/tmp/mysqltuner/{{ mysqltuner_version }}"

mysqltuner_defaults_directory: /etc/default

systemd_lib_directory: /lib/systemd/system

...
