---

- name: Ensure PostgreSQL databases are present.
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    lc_collate: "{{ item.lc_collate | default(omit) }}"
    lc_ctype: "{{ item.lc_ctype | default(omit) }}"
    locale_provider: "{{ item.locale_provider | default(omit) }}"
    icu_locale: "{{ item.icu_locale | default(omit) }}"
    encoding: "{{ item.encoding | default('UTF-8') }}"
    template: "{{ item.template | default('template0') }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_config_connections.socket.directories[0] | default('/run/postgresql')) }}"
    port: "{{ item.port | default(omit) }}"
    owner: "{{ item.owner | default(postgresql_user) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ postgresql_databases }}"
  loop_control:
    label: "{{ item.name }}, state: {{ item.state | default('present') }}"
  no_log: "{{ postgresql_log_security.suppress_user_log | default('true') }}"
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  # vars:
  #   ansible_facts.ssh_pipelining: true
