---

galaxy_info:
  role_name: mysqltuner
  namespace: bodsch

  author: Bodo Schulz
  description: ansible role to install and configure mysqltuner
  license: Apache
  min_ansible_version: "2.10"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 11
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - "database"
    - "mysql"
    - "mariadb"

dependencies: []
