---
name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - '.config/ansible-lint.yml'
      - '.yamllint'
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - '.config/ansible-lint.yml'
      - '.yamllint'

env:
  COLLECTION_NAMESPACE: bodsch
  COLLECTION_NAME: database
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

defaults:
  run:
    working-directory: 'ansible-collection-database'

jobs:
  arch:
    name: "${{ matrix.image }}: ${{ matrix.collection_role }} (ansible ${{ matrix.ansible-version }}, python ${{ matrix.python_version }})"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux:latest
        ansible-version:
          - '13.0'
        python_version:
          - "3.12"
        scenario:
          - default
        collection_role:
          - mariadb
          - postgresql
          - mariadb_backup

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v6.0.1
        with:
          path: 'ansible-collection-database'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: ðŸ set up python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install system packages
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
          sudo apt-get update -y
          sudo apt-get install -y python3-dateutil

      # - name: ansible version
      #   run: |
      #     ansible --version
      #
      # - name: install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r test-requirements.txt

      - name: force reinstall of community.docker
        run: |
          curl --silent \
            https://raw.githubusercontent.com/bodsch/ansible-toolbox/refs/heads/main/agc_install.py \
            > agc_install.py

          chmod +x agc_install.py

          ./agc_install.py community.docker --version 5.0.5

          # mkdir -p /home/runner/.ansible/tmp
          # mkdir -p /home/runner/.ansible/collections_offline
          #
          # cd /home/runner/.ansible/tmp
          # git clone https://github.com/ansible-collections/community.docker
          # cd community.docker
          #
          # ansible-galaxy collection build --verbose
          #
          # mv -v community-docker-*tar.gz /home/runner/.ansible/collections_offline
          #
          # #
          # mkdir -p /home/runner/.ansible/collections
          #
          # ansible-galaxy collection install \
          #   ./collections_offline/*.tar.gz \
          #   --force
          #
          # # ansible-galaxy collection install community.docker --force

      - name: Install collection
        run: |
          make \
            install

      - name: test with tox
        run: |
          make \
            test \
              -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
              -e DISTRIBUTION="${{ matrix.image }}" \
              -e COLLECTION_ROLE="${{ matrix.collection_role }}" \
              -e COLLECTION_SCENARIO="${{ matrix.scenario }}"
